name: Build Komodo Launcher

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qtbase5-dev-tools qt5-qmake build-essential

      - name: Build
        run: |
          mkdir build
          cd build
          qmake ../LauncherApp.pro
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KomodoLauncher-linux
          path: build/LauncherApp

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\\Qt'

      - name: Build
        shell: cmd
        env:
          QT_DIR: C:\Qt\Qt\5.15.2\msvc2019_64
        run: |
          REM Find Visual Studio installation path
          for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do (
            set "VS_PATH=%%i"
          )
          echo VS_PATH=%VS_PATH%
          if not defined VS_PATH (
            echo Error: Visual Studio path not found.
            exit /b 1
          )

          REM Set up MSVC environment
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          echo MSVC Environment set

          REM Verify the Qt directory
          echo Listing contents of %QT_DIR%\bin
          REM dir "%QT_DIR%\bin"

          REM Build the project
          mkdir build
          cd build
          "%QT_DIR%\bin\qmake.exe" ..\LauncherApp.pro
          if errorlevel 1 (
            echo qmake failed with exit code %errorlevel%
            exit /b %errorlevel%
          )
          REM dir
          nmake
          if errorlevel 1 (
            echo nmake failed with exit code %errorlevel%
            exit /b %errorlevel%
          )

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KomodoLauncher-windows
          path: build\release\LauncherApp.exe
